# Generated by Django 5.2.7 on 2025-11-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('documento', models.CharField(max_length=20)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('tipo_mascota', models.CharField(max_length=50)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.TimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
