# Generated by Django 5.2.7 on 2025-11-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_remove_carritoitem_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='review',
            name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='review',
            name='precio',
        ),
    ]
